### ISSUE TITLE
[Fork] ¡Escriba! A hybrid rich-text/Markdown editor for Qt.

### ISSUE THREAD

**Issue by DougBeney** [Anchakor/MRichTextEditor#3]
Hi!

Thank you for creating MRichTextEditor! It provided a great starting point for me in my open-source note-taking application I'm working on, [Vibrato Notes](https://vibrato.app/).

The name of the text-editor widget that is a fork of MRichTextEditor is named [Escriba]( https://openapplibrary.org/project/escriba).

**Comment by Anchakor** [comment]
@DougBeney Hi, thanks for letting me know! It looks useful, does the markdown editor update the rich text editor and visa versa? If so, you should mention it in the description, to market it better! :)

**Comment by DougBeney** [comment]
Yep! Uses MarkdownPanda for the html/markdown conversion between editors.
